<Project Sdk="TALXIS.DevKit.Build.Sdk/1.2.2">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <SolutionRootPath>__solution-declarations-root__</SolutionRootPath>
    <ProjectType>Solution</ProjectType>
    <GeneratePluginAssembly>__generate-plugin-assembly__</GeneratePluginAssembly>
  </PropertyGroup>
  <PropertyGroup Label="Dataverse solution metadata">
    <PublisherName>__publisher-name__</PublisherName>
    <PublisherPrefix>__publisher-prefix__</PublisherPrefix>
    <Version>1.0.0</Version>
  </PropertyGroup>
  <Target Name="Publish" />
</Project>
