# Initialize a Dataverse solution project using PAC CLI
pac solution init --publisher-name "examplepublisher" --publisher-prefix "examplepublisherprefix" --outputDirectory "SolutionLogicalNameExample"
cd "SolutionLogicalNameExample"

# Rename the src folder (produced by PAC CLI to remove the double src folder)
# and remove the unnecessary .gitignore file (we already have one in the repository root)
Rename-Item -Path .\src -NewName Declarations && Remove-Item .gitignore -Force

# Remove the default .cdsproj generated by PAC CLI; template already provides the .csproj
$cdsproj = Get-ChildItem -Path . -Filter *.cdsproj | Select-Object -First 1
if ($cdsproj) { Remove-Item $cdsproj.FullName -Force }

# Find the Solution.xml file and read it as XML
$solutionXml = Get-ChildItem -Path . -Filter Solution.xml -Recurse | Select-Object -First 1
[xml]$xml = Get-Content $solutionXml.FullName -Raw

# Find the UniqueName element and sanitize it
$uniqueName = $xml.ImportExportXml.SolutionManifest.UniqueName
$sanitized = [regex]::Replace($uniqueName, '[^a-zA-Z0-9]', '')
$xml.ImportExportXml.SolutionManifest.UniqueName = $sanitized

# Switch solution type to both to support packing managed solutions using SolutionPackager
$xml.ImportExportXml.SolutionManifest.Managed = 2

# Save the updated XML back to the file
$xml.Save($solutionXml.FullName)

cd ..

# Move the solution files from the temp folder to the root
Move-Item -Path "SolutionLogicalNameExample\*" -Destination . -Force
Remove-Item -Path "SolutionLogicalNameExample" -Force

# The new project is automatically added to the Visual Studio solution by the templating engine
# This would be an alternative: dotnet sln ../../ add SolutionLogicalNameExample.csproj"
